### ISSUE TITLE
No result when calling ConverseText 

### ISSUE THREAD

**Issue by CloudoguNguyen** [RecastAI/SDK-Golang#19]
Hi, I'm using the SDK Golang for recast.ai 3.2.0 and I'm get nil results when calling ConverseText

The code is like this 
```
client := recast.RequestClient{Token: RequestToken, Language:"en"}
response, err := client.ConverseText("Hows the weather", nil)
	if err != nil {
		// Do something
	}
fmt.println(response.Replies)
 ```

The bot skill is enabled, in business mode, and on the website I can get response from the bot well. But somehow I don't get replies when using the SDK. Anyone knows what I'm doing wrong here?

**Comment by dbousque** [comment]
Hi @CloudoguNguyen. The `converse` endpoint is depreciated, it uses the old bot-builder. For the new bot-builder, use `dialog` instead. There is no documentation on how to use it with this SDK, but can take a look at the code to find out :) https://github.com/RecastAI/SDK-Golang/blob/master/recast/dialog.go

**Comment by CloudoguNguyen** [comment]
Hi, @dbousque thanks you very much for your answer.
there is a last question of mine:
I see there is the function `resetConversation` in `conversation.go` using the depreciated converse endpoint, so I can't use it.

Is there any possibility to reset conversation in `dialog`?
