### ISSUE TITLE
reset conversation in dialog

### ISSUE THREAD

**Issue by CloudoguNguyen** [RecastAI/SDK-Golang#20]
Hi @dbousque,

thanks you very much for your answer in the last issue, but I think I'm having an another issue, sorry to bother you.

I see there is a function `resetConversation` in depreciated `Conversation.go`, so I'm not gonna use that.
But is there a possibility to reset conversation in `dialog`? 

Thanks you very much

**Comment by dbousque** [comment]
Hi @CloudoguNguyen, you can use 'update conversation' -> 'edit memory' -> 'reset memory' in a skill's actions, resetting the memory is equivalent to starting over.
