### ISSUE TITLE
Error while parsing time in TextRequest function

### ISSUE THREAD

**Issue by SebastienBoisard** [RecastAI/SDK-Golang#6]
Hi,

I've found an error while testing a small Recast/Go program with the new API version:

```Go
		response, err := recastClient.TextRequest("this is a test", nil)
		if err != nil {
			fmt.Println("TextRequest error: %s", err)
		}
```
And I received this error:

```
TextRequest error: parsing time ""2016-10-06T18:16:59.769174"" as ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "Z07:00"}
```

The problem seems to appear [while decoding the json response](https://github.com/RecastAI/SDK-Golang/blob/master/recast/client.go#L119):  

file: client.go
function: TextRequest
line: 111
instruction: `err = json.NewDecoder(bytes.NewBuffer(body)).Decode(&r)`

I've printed the body and the response seems to be ok:

```` 
body= {"results":{"uuid":"41647acc-b460-42c9-b914-c65d3e2b3c3d","source":"test2","intents":[{"slug":"eat","confidence":0.24},{"slug":"greetings","confidence":0.24},{"slug":"news","confidence":0.24},{"slug":"weather","confidence":0.24}],"act":"assert","type":"enty:currency","sentiment":"negative","entities":{},"language":"en","version":"2.0.0","timestamp":"2016-10-06T18:16:59.769174","status":200},"message":"Requests rendered with success"}
````

I've created a test to reproduce this error on [GoPlayground](https://play.golang.org/p/tuECgkvqtT) : 
```Go
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

type Response struct {
	Timestamp time.Time `json:"timestamp"`
}

func main() {

	body := `{"timestamp":"2016-10-06T18:16:59.769174","status":200}`
	var r Response

	err := json.NewDecoder(bytes.NewBufferString(body)).Decode(&r)
	if err != nil {
		fmt.Println("err=", err)
	}
}
```

Hope this help.

Sébastien.

**Comment by ftriquet** [comment]
Hi Sebastien,

Thank you for this issue, we recently changed the format of the timestamp we return fom the API, and it appears that golang's json decoding doesn't handle this format (ISO 8601). I'll fix it as as soon as possible.

François

**Comment by ftriquet** [comment]
@SebastienBoisard 
Hi  Sebastien I've got some news. It appears that the problem wasn't in the sdk itself but in the way we format the dates at Recast.AI. We are currently working on it. Thank you again for the feedback!

**Comment by SebastienBoisard** [comment]
Great! :smile:
